#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : imagesize
Version  : 1.1.0
Release  : 34
URL      : https://files.pythonhosted.org/packages/41/f5/3cf63735d54aa9974e544aa25858d8f9670ac5b4da51020bbfc6aaade741/imagesize-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/41/f5/3cf63735d54aa9974e544aa25858d8f9670ac5b4da51020bbfc6aaade741/imagesize-1.1.0.tar.gz
Summary  : Getting image size from png/jpeg/jpeg2000/gif file
Group    : Development/Tools
License  : MIT
Requires: imagesize-python3
Requires: imagesize-license
Requires: imagesize-python
BuildRequires : buildreq-distutils23
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-legacypython

%description
It parses image files' header and return image size.
        
        * PNG
        * JPEG
        * JPEG2000
        * GIF
        * TIFF (experimental)
        
        This is a pure Python library.

%package legacypython
Summary: legacypython components for the imagesize package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the imagesize package.


%package license
Summary: license components for the imagesize package.
Group: Default

%description license
license components for the imagesize package.


%package python
Summary: python components for the imagesize package.
Group: Default
Requires: imagesize-python3

%description python
python components for the imagesize package.


%package python3
Summary: python3 components for the imagesize package.
Group: Default
Requires: python3-core

%description python3
python3 components for the imagesize package.


%prep
%setup -q -n imagesize-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535958964
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export SOURCE_DATE_EPOCH=1535958964
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/imagesize
cp LICENSE.rst %{buildroot}/usr/share/doc/imagesize/LICENSE.rst
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/imagesize/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
